### PR TITLE
Support for Python bindings

### PR DESCRIPTION
**Pull request by j-rivero**
Being tested here: [Build Status](https://build.osrfoundation.org/job/sdformat13-debbuilder/249/)

### CODE REVIEW

**Comment by j-rivero** [comment]
Not good enough. Another try: [Build Status](https://build.osrfoundation.org/job/sdformat13-debbuilder/250/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
`python3-ignition-math7` is required

**Review by ahcorde — CHANGES_REQUESTED** [review]
conflicts

**Review by azeey — APPROVED** [review]
https://build.osrfoundation.org/job/sdformat13-debbuilder/251/ is green!

**Review by ahcorde — APPROVED** [review]

**Comment by azeey** [comment]
@j-rivero is this ready to be merged?

**Comment by j-rivero** [comment]
It is, the package is ready in the nightly repo https://build.osrfoundation.org/job/sdformat13-debbuilder/251/.

**Pull request merged**
